export const HENT_BRUKERINFO_FEILET = 'HENT_BRUKERINFO_FEILET';
export const HENTER_BRUKERINFO = 'HENTER_BRUKERINFO';
export const SET_BRUKERINFO = 'SET_BRUKERINFO';
export const SET_TIDSLINJE_ARBEIDSSITUASJON = 'SET_TIDSLINJE_ARBEIDSSITUASJON';
export const BRUKER_ER_INNLOGGET = 'BRUKER_ER_INNLOGGET';
export const BRUKER_ER_UTLOGGET = 'BRUKER_ER_UTLOGGET';
export const SJEKKER_INNLOGGING = 'SJEKKER_INNLOGGING';
export const SJEKK_INNLOGGING_FEILET = 'SJEKK_INNLOGGING_FEILET';
export const SJEKK_INNLOGGING_FORESPURT = 'SJEKK_INNLOGGING_FORESPURT';
export const HENT_BRUKERINFO_FORESPURT = 'HENT_BRUKERINFO_FORESPURT';

export const HENTER_DINE_SYKMELDINGER = 'HENTER_DINE_SYKMELDINGER';
export const HENT_DINE_SYKMELDINGER_FEILET = 'HENT_DINE_SYKMELDINGER_FEILET';
export const SET_DINE_SYKMELDINGER = 'SET_DINE_SYKMELDINGER';
export const SET_SORTERING = 'SET_SORTERING';
export const HENT_DINE_SYKMELDINGER_FORESPURT = 'HENT_DINE_SYKMELDINGER_FORESPURT';

export const HENT_LEDERE_FORESPURT = 'HENT_LEDERE_FORESPURT';
export const HENTER_LEDERE = 'HENTER_LEDERE';
export const LEDERE_HENTET = 'LEDERE_HENTET';
export const HENT_LEDERE_FEILET = 'HENT_LEDERE_FEILET';

export const HENT_VEDLIKEHOLD_FEILET = 'HENT_VEDLIKEHOLD_FEILET';
export const HENTER_VEDLIKEHOLD = 'HENTER_VEDLIKEHOLD';
export const VEDLIKEHOLD_HENTET = 'VEDLIKEHOLD_HENTET';
export const HENT_VEDLIKEHOLD_FORESPURT = 'HENT_VEDLIKEHOLD_FORESPURT';
